### ISSUE TITLE
In Raku you can have a postfix `if` followed by a postfix `for`

### ISSUE THREAD

**Issue by lizmat** [heyajulia/rakumagic#1]
# Snippet

```raku
say "$_ is even" if $_ %% 2 for ^5
# 0 is even
# 2 is even
# 4 is even
```

# Comment

In Raku, contrary to e.g. Perl, you *can* have a postfix `for` after a postfix `if` for more succinct looping and checking.

**Comment by heyajulia** [comment]
Thank you for your submission, Liz!

Tweeted: https://twitter.com/rakumagic/status/1370041254822744068
