### ISSUE TITLE
Flipping a coin, rolling dice

### ISSUE THREAD

**Issue by lizmat** [heyajulia/rakumagic#3]
# Snippet

```raku
say Bool.roll;       # True or False
say (1..6).roll(2);  # e.g. (3 4)
```

# Comment

The `roll` method can be called on enums such as `Bool` to randomly select one of its members.  Or can be called on ranges.  And one can also specify how many "rolls" one wants.

**Comment by heyajulia** [comment]
Thanks as always, Liz!

Tweeted here: https://twitter.com/rakumagic/status/1372561450607185920?s=20
