### ISSUE TITLE
The 5 most uncommon letters in your language

### ISSUE THREAD

**Issue by lizmat** [heyajulia/rakumagic#4]
# Snippet

```raku
.say for "/usr/share/dict/words".IO.slurp.lc.comb.grep("a".."z").Bag.sort(*.value).head(5)
```

# Comment

Read the word list for your language (on Linux: `/usr/share/dict/words`) by turning the string into an `IO` object and then reading the whole file into memory (`.slurp`).  Then lowercase the string (`.lc`), decompose the string into its characters (`.comb`), only use the letters (`.grep("a".."z")`), turn that into a hash with the letters as keys, and the frequency as values (`.Bag`).  Then sort that on the values (`.sort(*.value)`) and limit on the first five (`.head(5)`).  Print the letter and frequency while iterating over that (`.say for`).

**Comment by lizmat** [comment]
Maybe a bit long, but I thought it'd be a nice combination of a number of Raku features.

**Comment by heyajulia** [comment]
Tweeted here: https://twitter.com/rakumagic/status/1376576857445916676

(Thanks again!)
