### ISSUE TITLE
Coercion FTW

### ISSUE THREAD

**Issue by lizmat** [heyajulia/rakumagic#5]
# Snippet

```raku
my $date = "2021-04-22".Date;
say $date.raku;  # Date.new(2021,4,22)

my Date() $date = "2021-04-22";  # same using new coercion protocol
```
Coercing a string into a Date is very simple.  If the string is in the correct format (YYYY-MM-DD), of course.

**Comment by heyajulia** [comment]
Hey Liz!

First of all, I'm _very_ sorry for the delay. Thanks for submitting another snippet!

I've tweeted it here: https://twitter.com/rakumagic/status/1390249326463623168?s=20
