### ISSUE TITLE
The sleepsort algorithm

### ISSUE THREAD

**Issue by lizmat** [heyajulia/rakumagic#6]
# Snippets

```raku
my @random = (1..10).pick(*);
say @random;
await @random.map: { start { sleep $_; .say } }
```

# Comment

There are many algorithms for sorting.  The sleepsort algorithm is one of the more silly ones.

**Comment by heyajulia** [comment]
I kept telling myself I'd tweet this someday, but I kept forgetting. Sorry, Liz!

Either way, I just tweeted it out: https://twitter.com/rakumagic/status/1463892057827774464
